version: '3'

services:
  db:
    image: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: casadamiao
      MYSQL_DATABASE: casadamiao
    ports:
      - "3307:3306"
    volumes:
      - container-volume:/var/lib/mysql
      - ./data.sql:/docker-entrypoint-initdb.d/dump.sql
volumes:
  container-volume: